import { useState } from 'react'
import { useUIStore } from '../../stores/uiStore'
import { triggerReconnect } from '../../stores/connectionStore'
import { apiFetch } from '../../utils/api'
import { showToast } from '../../utils/toast'
import type { Settings } from '../../types'

interface Props {
  s: Settings
  update: (p: Partial<Settings>) => void
}

export function NetworkTab({ s, update }: Props) {
  const [serverIp, setServerIp] = useState(s.serverIp)
  const [linkCode, setLinkCode] = useState(s.linkCode)
  const [pairStatus, setPairStatus] = useState<React.ReactNode>(null)
  const closeSettings = useUIStore((st) => st.closeSettings)

  const handleRestartServer = () => {
    const trimmed = serverIp.trim() || '127.0.0.1'
    update({ serverIp: trimmed })
    window.electronAPI?.restartServer?.(trimmed)
    triggerReconnect()
    showToast('Server restarting…', 'info')
  }

  const handlePair = async () => {
    const code = linkCode.trim().toUpperCase()
    if (code.length !== 5) {
      setPairStatus(<span style={{ color: 'var(--atm-red)' }}>Code must be 5 characters.</span>)
      return
    }
    setPairStatus(<span style={{ color: 'var(--atm-blue)' }}>Checking connection…</span>)
    try {
      const res = await apiFetch(`/api/pair/${code}`)
      const result = await res.json()
      if (result.success) {
        setPairStatus(<span style={{ color: 'var(--atm-green)' }}>Paired successfully!</span>)
        update({ linkCode: code })
        triggerReconnect()
        setTimeout(() => closeSettings(), 1000)
      } else {
        setPairStatus(<span style={{ color: 'var(--atm-red)' }}>{result.message}</span>)
      }
    } catch {
      setPairStatus(
        <span style={{ color: 'var(--atm-red)' }}>
          Gateway not found. Ensure server.js is running.
        </span>,
      )
    }
  }

  return (
    <>
      <div className="pane-header">
        <h3>Network &amp; Connectivity</h3>
        <p>Manage your connection to the gateway</p>
      </div>

      <div className="settings-card">
        <div style={{ display: 'block' }}>
          <div className="settings-info" style={{ marginBottom: 12 }}>
            <div className="settings-label">Server IP</div>
            <div className="settings-description">
              The IP address your local StripCol gateway listens on.
            </div>
          </div>
          <div className="input-with-button">
            <span className="material-icons input-icon">lan</span>
            <input
              type="text"
              className="sys-input-text"
              style={{ width: '100%' }}
              placeholder="127.0.0.1"
              value={serverIp}
              onChange={(e) => setServerIp(e.target.value)}
              onMouseDown={(e) => e.stopPropagation()}
            />
          </div>
          <button
            className="custom-btn primary"
            style={{ width: '100%', marginTop: 12 }}
            onClick={handleRestartServer}
          >
            <span className="material-icons">refresh</span> Restart &amp; Connect
          </button>
        </div>
      </div>

      <div className="settings-card" style={{ marginTop: 12 }}>
        <div style={{ display: 'block' }}>
          <div className="settings-info" style={{ marginBottom: 12 }}>
            <div className="settings-label">Link Code</div>
            <div className="settings-description">
              Enter the 5-digit code generated by Euroscope.
            </div>
          </div>
          <div className="input-with-button combo">
            <span className="material-icons input-icon">vpn_key</span>
            <input
              type="text"
              className="sys-input-text"
              style={{ flexGrow: 1 }}
              placeholder="ABC12"
              maxLength={5}
              value={linkCode}
              onChange={(e) => setLinkCode(e.target.value.toUpperCase())}
              onMouseDown={(e) => e.stopPropagation()}
              onKeyDown={(e) => { if (e.key === 'Enter') handlePair() }}
            />
            <button className="custom-btn primary no-radius-left" onClick={handlePair}>
              Pair
            </button>
          </div>
          {pairStatus && (
            <div id="pairingStatus" className="status-msg" style={{ textAlign: 'center', marginTop: 12 }}>
              {pairStatus}
            </div>
          )}
        </div>
      </div>
    </>
  )
}
